language: node_js

# https://github.com/travis-ci/travis-ci/issues/9561#issuecomment-488997608
# "node-sass currently does not work with node version 12"
node_js: 11.10.0

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - "~/.cache"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version

before_script:
  - yarn start &

after_success:
  - yarn run coveralls

deploy:
  provider: heroku
  app: colibri-reading-app
  api_key:
    secure: ZBY9gMMwcV5QRve5ZqObdozHb8iN/b/MV5h+e+3DceBxyzp51k0jeFIqlMYa/IBqQecVG2vFvYQsOLccMSe32QwLDC9PVmY3/al88Y5ua4FvAhN6eEAURsujIy/vZ2BEjrM39bLV9ZeK+ZYQP8jjLPzyVgikUX1Qzc2n4RZCXQIGKPSvkFvWF9zzS1rCr36TKTpKxU4tIk4z6Zu8AL/snKrogdKRmSKbISqwbXS8/lDkAXzKSpRIlSbLTwfFqwLcK5gXdfgOM1TXOVnhwuPKjbOY98HzbXH2Ggeo/DD6KMlUXlNUELjdp/PPhXgT53TDfDCvhXuNJrFhcwulD3vJxQRtBYVOW/nn821SONZBP84goJ0OEK2IH9cYvYXNBZbHR1JEjvEku3zCQgFpX6B5hggw+r+AXlATk/DR4NB5jv/xcszSdn+QgrK2PGevxbJes1m2hIrI5PBXI0YO/wFTssgKZjbhpVqkNljyJGYgd30y/FbYgNYbJz/RaE/qdntjewKXqrGn28qvg/vg7icZvBt8b+8OfswB8DoTOKmugVWYOMSvr/fkjT2gRYQ9xlaK6/MQv5W6wbUwyRO9YSYRRFX/oEKbtuTcpofvcHnVE+dXpiBfvBEI2LZkcNhgadFJQGgkNGygvoN/1N0yVM+9s5aN5V+94cCM4jb+Us+jQ3k=
